Repository VividSeats/vivid-design-patterns, pull requests merged in 2019-12, with the labels that each got.

#133 fix styles for nested accordions
  src/styles/_collapse.scss
Labels: review

#130 Com 764
  src/components/atoms/Icon.jsx
  src/styles/_icon.scss
Labels: review

#135 DOT-1268 fix height of legacy banners to handle affiliate image height
  src/styles/_banner.scss
Labels: review

#139 Icon doc
  docs/Foundation/Icons.mdx
  docs/IconExample.jsx
  docs/IconGrid.jsx
  doczrc.js
  package.json
Labels: documentation, review

#136 DOT-432 Add utm medium to event urls
  src/components/molecules/EventRow.jsx
  test/EventRow/EventRowSpec.js
Labels: review

#143 DSYS-39 include typography in components
  src/styles/_badge.scss
  src/styles/_carousel.scss
  src/styles/_chips.scss
  src/styles/_controls.scss
  src/styles/_fab.scss
  src/styles/_filterGroups.scss
  src/styles/_helperText.scss
  src/styles/_heros.scss
  src/styles/_inputs.scss
  src/styles/_layout.scss
  src/styles/_search.scss
  src/styles/_tabs.scss
  src/styles/_toggle.scss
  src/styles/_typeahead.scss
  src/styles/_typography.scss
  src/styles/mixins/_mixins.scss
Labels: enhancement, review

#145 DOT-1351 adds card hero parent to non background image card heros
  src/components/atoms/CardHero.jsx
Labels: bug, review

#146 DOT-659 adds utilities styles
  docs/Foundation/Utilities.mdx
  docs/docz.scss
  src/styles/_utilities.scss
Labels: enhancement, review

#147 Adds negative margin utils
  docs/Foundation/Utilities.mdx
  src/styles/_utilities.scss
Labels: enhancement

#144 DOT-724 add country code to events
  src/components/molecules/Banner.jsx
  src/components/molecules/EventRow.jsx
  src/components/molecules/ExpandableContent.jsx
  src/components/molecules/Form.jsx
  src/components/molecules/TextField.jsx
  test/TypeStyles/TypographySpec.js
Labels: review

#150 UXD-2781 add padding to hero subtitle
  src/styles/_heros.scss
Labels: bug

#151 UXD-2781 adjust hero subtitle margin
  src/styles/_heros.scss
Labels: bug

#152 Add `nofollow` to `rel` attribute to links to production pages with no tickets available
  src/components/molecules/EventRow.jsx
  test/EventRow/EventRowSpec.js
Labels: enhancement

#155 DOT-865 adjust breakpoints
  src/styles/_search.scss
  src/styles/_tokens.scss
Labels: bug
