Repository VividSeats/vivid-design-patterns, pull requests merged in 2020-02, with the labels that each got.

#164 Dot 1263
  docs/Components/EventCard.mdx
  docs/Components/EventRow.mdx
  package.json
  src/components/atoms/CardHero.jsx
  src/components/molecules/EventCard.jsx
  src/components/molecules/EventRow.jsx
  src/index.js
  test/Card/CardSpec.js
  test/EventCard/EventCardSpec.js
  test/EventRow/EventRowSpec.js
  yarn.lock
Labels: enhancement, review

#169 DOT-1749 remove background style attributes from image component
  src/components/atoms/Image.jsx
Labels: bug, review

#167 Update loading spinner import
  docs/Components/LoadingSpinner.mdx
Labels: documentation

#171 DSYS-72 fixes event row button width and large grouped buttons
  docs/Components/EventRow.mdx
  src/components/molecules/EventRow.jsx
  src/styles/_button.scss
  src/styles/_eventRow.scss
Labels: bug, review

#172 DSYS-73 create trigger component
  docs/Components/Trigger.mdx
  docs/docz.scss
  src/components/atoms/Trigger.jsx
  src/index.js
  src/styles/_trigger.scss
  test/Trigger/TriggerSpec.js
Labels: enhancement, review

#170 DOT-1774 make entire EventCard into a link
  src/components/molecules/Accordion.jsx
  src/components/molecules/Card.jsx
  src/components/molecules/EventCard.jsx
  src/components/molecules/Form.jsx
  src/components/molecules/Select.jsx
  test/TypeStyles/TypographySpec.js
Labels: bug

#174 eslint-changes to satisfy eslint when publishing
  src/components/molecules/Accordion.jsx
  src/components/molecules/Card.jsx
  src/components/molecules/Form.jsx
  src/components/molecules/Select.jsx
Labels: bug

#175 DSYS-74 add additional type props
  src/styles/_typography.scss
  src/utils/typographyUtils.js
Labels: enhancement, review

#176 DSYS-75 add truncate prop to event row
  src/components/molecules/EventCard.jsx
  src/components/molecules/EventRow.jsx
  src/styles/_eventRow.scss
Labels: enhancement, review
