Repository VividSeats/vivid-design-patterns, pull requests merged in 2020-01, with the labels that each got.

#156 DOT-1393 adds hero breadcrumb margin
  src/styles/_heros.scss
Labels: bug

#158 DSYS-45 adds responsive flexwrap classes to grid.scss
  src/styles/_grid.scss
Labels: enhancement, review

#149 update grid components with more documentation and props
  docs/Components/Column.mdx
  docs/Components/Grid.mdx
  docs/Components/Row.mdx
  docs/Components/TextField.mdx
  docs/GridItem.jsx
  src/components/molecules/Column.jsx
  src/components/molecules/Row.jsx
  src/styles/_typography.scss
  src/styles/_utilities.scss
  test/TypeStyles/TypographySpec.js
Labels: enhancement

#160 Make className an optional type for Typeahead component
  src/index.d.ts
Labels: documentation

#161 DOT-1536 hide horizontal scrollbar for hero tabs
  src/styles/_heros.scss
Labels: bug, review

#162 DOT-1273 update event row with thumbnail
  docs/Components/EventRow.mdx
  src/components/molecules/EventRow.jsx
  src/styles/_eventRow.scss
  test/EventRow/EventRowSpec.js
Labels: enhancement

#163 Add Image Tag Componetn
  docs/Components/Image.mdx
  package.json
  src/components/atoms/Image.jsx
  src/components/molecules/EventRow.jsx
  test/Image/ImageSpec.js
Labels: enhancement
